# Use the official OpenJDK 11 image as base
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the packaged Spring Boot application JAR file into the container
COPY target/your-application.jar app.jar

# Expose the port that your Spring Boot application runs on
EXPOSE 8081

# Specify the command to run your Spring Boot application when the container starts
CMD ["java", "-jar", "app.jar"]